### ISSUE TITLE
Incorrectly set flags as Tails in Adventure Fields

### ISSUE THREAD

**Issue by ItsEasyActually** [ClassicSpeed/sadx-classic-randomizer#553]
When playing as Tails, after using any of the entrances in the Angel Island portion of the Mystic Ruins (Icecap, Red Mountain, and The Past), the following happens:
- His soundbank is switched to Knuckles soundbank
- The ladder in Icecap (if applicable for the session) will disappear

The issues will persist while in the Mystic Ruins, but entering another Adventure Field or any level that's anywhere else seems to fix the messed up flag when returning to the Adventure Fields.

It definitely appears some flags are being set incorrectly when returning to the Angel Island area. Best guess is that the game believes Knuckles is the active character even though it's Tails given the Icecap ladder disappears. A bit odd since my session should have Knuckles visiting Icecap (its entrance is shuffled to Sky Deck), but I do not have access to Knuckles yet for this session. I will report back if there's any additional issues with him once he's been unlocked for me.

Outside of that, if I can provide any further information, lemme know.

---
These are the settings used for this session just in case it's related to one of the settings that was toggled.
```yaml
game: Sonic Adventure DX
requires:
  version: 0.6.1 # Version of Archipelago required for this yaml to work as expected.

Sonic Adventure DX:
  # Game Options
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # 
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # 
    # **Full:** ensure everything can be reached and acquired.
    # 
    # **Minimal:** ensure what is needed to reach your goal can be acquired.
    full: 50
    minimal: 0

  death_link:
    # When you die, everyone who enabled death link dies. Of course, the reverse is true too.
    'false': 0
    'true': 50

  # General Options
  goal_requires_levels:
    # If enabled, you have to complete action stages to unlock the last fight.
    'false': 0
    'true': 50

  levels_percentage:
    # If Levels are part of the goal, Percentage of the available levels that needed to be completed to unlock the final story.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 25
    # Maximum value is 100
    100: 100
    random: 0
    random-low: 0
    random-high: 0

  goal_requires_chaos_emeralds:
    # If enabled, you have to collect all the Chaos Emeralds to unlock the last fight.
    # Keep in mind selecting emerald hunt will require enough checks to add the 7 emeralds to the pool.
    'false': 0
    'true': 50

  goal_requires_emblems:
    # If enabled, you have to collect a certain number of emblems to unlock the last fight.
    # The emblems are extra items added to the item pool, so they scale with the number of checks.
    'false': 0
    'true': 50

  max_emblem_cap:
    # If Emblems are part of the goal, determines the maximum number of emblems that can be in the item pool.
    # If fewer available locations exist in the pool than this number, the number of available locations will be used instead.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 20
    # Maximum value is 1500
    130: 0
    random: 50
    random-low: 0
    random-high: 0

  emblems_percentage:
    # If Emblems are part of the goal, percentage of the available emblems needed to unlock the final story.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 90
    75: 0
    random: 0
    random-low: 0
    random-high: 50

  goal_requires_missions:
    # If enabled, you have to complete missions to unlock the last fight.
    'false': 0
    'true': 50

  mission_percentage:
    # If Missions are part of the goal, Percentage of the available missions that needed to be completed to unlock the final story.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 25
    # Maximum value is 100
    100: 0
    random: 50
    random-low: 0
    random-high: 0

  goal_requires_bosses:
    # If enabled, you have to beat all the bosses to unlock the last fight.
    'false': 0
    'true': 50

  boss_percentage:
    # If Bosses are part of the goal, Percentage of the available bosses that needed to be completed to unlock the final story.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 25
    # Maximum value is 100
    100: 0
    random: 50
    random-low: 0
    random-high: 0

  goal_requires_chao_races:
    # If enabled, you have to beat all the chao races to unlock the last fight.
    'false': 50
    'true': 0

  logic_level:
    # Determines the logic the randomizer will use.
    # Normal Logic (0): Very forgiving, ideal if you are not used to this game or its location checks.
    # Hard Logic (1): Less forgiving logic, some checks require performing spindash jumps or dying to get the check.
    # Expert DC Logic (2): The most unforgiving logic, some checks require performing out-of-bounds jumps (DC conversion).
    # Expert DX Logic (3): The most unforgiving logic, some checks require performing out-of-bounds jumps (vanilla DX).
    normal_logic: 0
    hard_logic: 50
    expert_dc_logic: 0
    expert_dx_logic: 0

  starting_character:
    # Select which the character you will start with.
    # Choose between Random (0), Sonic (1), Tails (2), Knuckles (3), Amy (4), Big (5), and Gamma (6).
    random_character: 50
    sonic: 0
    tails: 0
    knuckles: 0
    amy: 0
    big: 0
    gamma: 0

  starting_location:
    # Select in which location you would like to start.
    # Keep in mind that if there are no checks in that location for your character, another one will be chosen.
    # CChoose between Random (0), Station Square (Main) (1), Station (2), Hotel (3), Casino (4), Twinkle Park Lobby (5),
    # Mystic Ruins (Main) (6), Angel Island (7), Jungle (8) and EggCarrier (Outside) (9), EggCarrier (Inside) (10)
    random_location: 50
    station_square_main: 0
    station: 0
    hotel: 0
    casino: 0
    twinkle_park_lobby: 0
    mystic_ruins_main: 0
    angel_island: 0
    jungle: 0
    egg_carrier_outside: 0
    egg_carrier_inside: 0

  random_starting_location_per_character:
    # If enabled, each character will start in a random location.
    'false': 0
    'true': 50

  guaranteed_starting_checks:
    # Ensures at least this many checks in your starting location if possible.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    2: 0
    random: 50
    random-low: 0
    random-high: 0

  entrance_randomizer:
    # Randomizes the entrances to action stages.
    # This means that the entrance to an action stage could be different from the original game.
    # If a given entrance is closed (e.g., doors not opening), it indicates that the level behind that entrance is not accessible.
    # For example, if Hot Shelter is inside the Emerald Coast entrance, the beach entrance will appear closed for Sonic but open for Amy.
    # Depending on the character, the entrance may be Sonic's or Knuckles'. Big, for example, can't use the Speed Highway elevator.
    'false': 0
    'true': 50

  level_entrance_plando:
    # Plando for level entrance. Only works if Entrance Randomizer is enabled.
    # The level name should be Capitalized with no spaces.
    # For example, {'Emerald Coast': 'Final Egg'} will place Final Egg behind the Emerald Coast entrance and randomize the rest.
    {}

  send_death_link_chance:
    # When dying, the chance of sending a death link to another player.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 100
    100: 50
    random: 0
    random-low: 0
    random-high: 0

  receive_death_link_chance:
    # When receiving a death link, the chance of dying.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 100
    100: 50
    random: 0
    random-low: 0
    random-high: 0

  ring_link:
    # Whether your in-level ring gain/loss is linked to other players.
    'false': 50
    'true': 0

  casinopolis_ring_link:
    # Whether Ring Link is enabled while playing Sonic's Casinopolis.
    'false': 50
    'true': 0

  hard_ring_link:
    # If Ring Link is enabled, sends and receives rings in more situations.
    # Particularly, it will subtract rings when finishing a level and during the Perfect Chaos fight.
    'false': 50
    'true': 0

  ring_loss:
    # How taking damage is handled.
    # Classic (0): You lose all of your rings when hit.
    # Modern (1): You lose 20 rings when hit.
    # One Hit K.O. (2): You die immediately when hit.
    # One Hit K.O. No Shields (3): You die immediately when hit, and you can't use shields or invincibility power ups.
    classic: 50
    modern: 0
    one_hit_k_o: 0
    one_hit_k_o_no_shields: 0

  # Characters Options
  playable_sonic:
    # Determines whether Sonic is playable.
    'false': 0
    'true': 50

  playable_tails:
    # Determines whether Tails is playable.
    'false': 0
    'true': 50

  playable_knuckles:
    # Determines whether Knuckles is playable.
    'false': 0
    'true': 50

  playable_amy:
    # Determines whether Amy is playable.
    'false': 0
    'true': 50

  playable_big:
    # Determines whether Big is playable.
    'false': 0
    'true': 50

  playable_gamma:
    # Determines whether Gamma is playable.
    'false': 0
    'true': 50

  # Stage Options
  sonic_action_stage_missions:
    # Choose what action stage missions will be a location check for Sonic.
    none: 0
    c: 0
    c_b: 0
    c_b_a: 50
    c_b_a_s: 50

  tails_action_stage_missions:
    # Choose what action stage missions will be a location check for Tails.
    none: 0
    c: 0
    c_b: 0
    c_b_a: 50
    c_b_a_s: 50

  knuckles_action_stage_missions:
    # Choose what action stage missions will be a location check for Knuckles.
    none: 0
    c: 0
    c_b: 0
    c_b_a: 50
    c_b_a_s: 50

  amy_action_stage_missions:
    # Choose what action stage missions will be a location check for Amy.
    none: 0
    c: 0
    c_b: 0
    c_b_a: 50
    c_b_a_s: 50

  big_action_stage_missions:
    # Choose what action stage missions will be a location check for Big.
    none: 0
    c: 0
    c_b: 0
    c_b_a: 50
    c_b_a_s: 50

  gamma_action_stage_missions:
    # Choose what action stage missions will be a location check for Gamma.
    none: 0
    c: 0
    c_b: 0
    c_b_a: 50
    c_b_a_s: 50

  # Upgrade Options
  randomized_sonic_upgrades:
    # Determines whether Sonic's upgrades are randomized and sent to the item pool.
    'false': 0
    'true': 50

  randomized_tails_upgrades:
    # Determines whether Tails' upgrades are randomized and sent to the item pool.
    'false': 0
    'true': 50

  randomized_knuckles_upgrades:
    # Determines whether Knuckles' upgrades are randomized and sent to the item pool.
    'false': 0
    'true': 50

  randomized_amy_upgrades:
    # Determines whether Amy's upgrades are randomized and sent to the item pool.
    'false': 0
    'true': 50

  randomized_big_upgrades:
    # Determines whether Big's upgrades are randomized and sent to the item pool.
    'false': 0
    'true': 50

  randomized_gamma_upgrades:
    # Determines whether Gamma's upgrades are randomized and sent to the item pool.
    'false': 0
    'true': 50

  # Bosses Options
  boss_checks:
    # Determines whether beating a boss grants a check (15 Locations).
    'false': 0
    'true': 50

  unify_chaos4:
    # Determines whether the Chaos 4 fight counts as a single location or three (Sonic, Tails, and Knuckles).
    'false': 50
    'true': 0

  unify_chaos6:
    # Determines whether the Chaos 6 fight counts as a single location or three (Sonic, Big, and Knuckles).
    'false': 50
    'true': 0

  unify_egg_hornet:
    # Determines whether the Egg Hornet fight counts as a single location or two (Sonic, Tails).
    'false': 50
    'true': 0

  # Extra locations
  field_emblems_checks:
    # Determines whether collecting field emblems grants checks (12 Locations).
    'false': 0
    'true': 50

  chao_egg_checks:
    # Determines whether getting the 3 secret chao eggs grants checks (3 Locations).
    'false': 0
    'true': 50

  chao_races_checks:
    # Determines whether winning the chao races grants checks (5 Locations).
    'false': 50
    'true': 0

  chao_races_levels_to_access_percentage:
    # Percentage of the available levels accessible for the chao races to be in logic.
    # Higher values means races are required later in the game.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 25
    # Maximum value is 100
    100: 0
    random: 0
    random-low: 0
    random-high: 0

  mission_mode_checks:
    # Determines whether completing missions grants checks (60 Locations).
    'false': 0
    'true': 50

  auto_start_missions:
    # Determines whether missions will start already activated.
    'false': 50
    'true': 0

  mission_blacklist:
    # Determines what missions are blacklisted. The default are:
    # Mission 49 (Flags in the Kart section of Twinkle Park).
    # Mission 53 (Triple Jump in the Snowboard section of Ice Cap).
    # Mission 54 (Flags in the Snowboard section of Ice Cap).
    # Mission 58 (Flags in the rolling bounce section of Lost World).
    ['53']

  twinkle_circuit_check:
    # Determines whether beating Twinkle Circuit grants a check.
    'false': 0
    'true': 50

  twinkle_circuit_multiple_check:
    # If enabled, each character will have their own Twinkle Circuit check (5 extra locations).
    # Only works if Twinkle Circuit Check is enabled.
    'false': 0
    'true': 50

  sand_hill_check:
    # Determines whether beating Sand Hill grants a check.
    'false': 0
    'true': 50

  sand_hill_check_hard:
    # Determines whether beating the harder (points-based) Sand Hill mission grants a check.
    # Only works if Sand Hill Check is enabled.
    'false': 0
    'true': 50

  sky_chase_checks:
    # Determines whether beating Sky Chase Act 1 and 2 grants checks (2 Locations).
    'false': 0
    'true': 50

  sky_chase_checks_hard:
    # Determines whether beating the harder (points-based) Sky Chase Act 1 and 2 missions grants checks (2 Locations).
    # Only works if Sky Chase checks are enabled.
    'false': 0
    'true': 50

  enemy_sanity:
    # Determines whether destroying enemies grants checks (710 Locations).
    # You need to enable enemy-sanity for some characters for it to work.
    'false': 50
    'true': 0

  sonic_enemy_sanity:
    # If enemy-sanity is on, determines whether Sonic's enemies are part of the randomizer (308 Locations).
    'false': 0
    'true': 50

  tails_enemy_sanity:
    # If enemy-sanity is on, determines whether Tails' enemies are part of the randomizer (46 Locations).
    'false': 0
    'true': 50

  knuckles_enemy_sanity:
    # If enemy-sanity is on, determines whether Knuckles' enemies are part of the randomizer (80 Locations).
    'false': 0
    'true': 50

  amy_enemy_sanity:
    # If enemy-sanity is on, determines whether Amy's enemies are part of the randomizer (54 Locations).
    'false': 0
    'true': 50

  big_enemy_sanity:
    # If enemy-sanity is on, determines whether Big's enemies are part of the randomizer (12 Locations).
    'false': 0
    'true': 50

  gamma_enemy_sanity:
    # If enemy-sanity is on, determines whether Gamma's enemies are part of the randomizer (210 Locations).
    'false': 0
    'true': 50

  capsule_sanity:
    # Determines whether destroying capsules grants checks (692 Locations).
    # You need to enable capsule-sanity for some characters and some types for it to work.
    'false': 50
    'true': 0

  pinball_capsules:
    # Determines whether pinball's capsules grant checks (5 Locations).
    'false': 50
    'true': 0

  sonic_capsule_sanity:
    # If capsule-sanity is on, determines whether Sonic's capsules are part of the randomizer (360 Locations).
    'false': 0
    'true': 50

  tails_capsule_sanity:
    # If capsule-sanity is on, determines whether Tails' capsules are part of the randomizer (111 Locations).
    'false': 0
    'true': 50

  knuckles_capsule_sanity:
    # If capsule-sanity is on, determines whether Knuckles' capsules are part of the randomizer (66 Locations).
    'false': 0
    'true': 50

  amy_capsule_sanity:
    # If capsule-sanity is on, determines whether Amy's capsules are part of the randomizer (53 Locations).
    'false': 0
    'true': 50

  big_capsule_sanity:
    # If capsule-sanity is on, determines whether Big's capsules are part of the randomizer (26 Locations).
    'false': 0
    'true': 50

  gamma_capsule_sanity:
    # If capsule-sanity is on, determines whether Gamma's capsules are part of the randomizer (76 Locations).
    'false': 0
    'true': 50

  life_capsule_sanity:
    # If capsule-sanity is on, the randomizer will include Life Capsules (103 Locations).
    'false': 0
    'true': 50

  shield_capsule_sanity:
    # If capsule-sanity is on, the randomizer will include  Shields and Magnetic Shields (78 Locations).
    'false': 0
    'true': 50

  powerup_capsule_sanity:
    # If capsule-sanity is on, the randomizer will include Invincibility, Speed Up and Bomb Capsules (70 Locations).
    'false': 0
    'true': 50

  ring_capsule_sanity:
    # If capsule-sanity is on, the randomizer will include 5, 10 and ? capsules (441 Locations).
    'false': 0
    'true': 50

  fish_sanity:
    # Determines whether catching every type of fish grants checks (23 Locations).
    'false': 50
    'true': 0

  lazy_fishing:
    # Enabling Lazy Fishing does two things:
    # Grants infinite tension during fishing if you have the Power Rod upgrade.
    # Adds the Power Rod as a logic requirement for all fish in fish-sanity, B/A/S ranks and every "Keeper" mission for Big.
    'false': 50
    'true': 0

  # Junk Options
  junk_fill_percentage:
    # Replace a percentage of non-required emblems in the item pool with random junk items.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 100
    50: 50
    random: 0
    random-low: 0
    random-high: 0

  trap_fill_percentage:
    # Replace a percentage of junk items in the item pool with random traps.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 100
    0: 0
    random: 50
    random-low: 0
    random-high: 0

  ice_trap_weight:
    # Likelihood of receiving a trap that freezes the player in place.
    none: 0
    low: 50
    medium: 50
    high: 0

  spring_trap_weight:
    # Likelihood of receiving a trap that spawns a spring that sends the player flying in the opposite direction.
    none: 0
    low: 50
    medium: 50
    high: 0

  police_trap_weight:
    # Likelihood of receiving a trap that spawns a lot of Cop Speeder enemies.
    none: 0
    low: 50
    medium: 50
    high: 0

  buyon_trap_weight:
    # Likelihood of receiving a trap that spawns a lot of Buyon enemies.
    none: 0
    low: 50
    medium: 0
    high: 0

  reverse_trap_weight:
    # Likelihood of receiving a trap that reverses your controls.
    none: 50
    low: 0
    medium: 0
    high: 0

  gravity_trap_weight:
    # Likelihood of receiving a trap that increments your gravity.
    none: 50
    low: 0
    medium: 0
    high: 0

  reverse_trap_duration:
    # How many seconds the reverse control trap will last. If set to 0, the trap will last until you die or change level.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 60
    10: 50
    random: 0
    random-low: 0
    random-high: 0

  traps_and_filler_on_adventure_fields:
    # If enabled, traps and filler can activate in the adventure field.
    'false': 0
    'true': 50

  traps_and_filler_on_boss_fights:
    # If enabled, traps and filler can activate during boss fights.
    'false': 0
    'true': 50

  traps_and_filler_on_perfect_chaos_fight:
    # If enabled, traps and filler can activate during the Perfect Chaos fight.
    # Keep in mind that enemy traps will subtract rings from the player.
    'false': 50
    'true': 0

  # Item & Location Options
  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_hints:
    # Start with these item's locations prefilled into the ``!hint`` command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the ``!hint`` command.
    []

  exclude_locations:
    # Prevent these locations from having an important item.
    []

  priority_locations:
    # Prevent these locations from having an unimportant item.
    []

  item_links:
    # Share part of your item pool with other players.
    []
```
